blueprint:
  name: Tesla EV Solar Excess Charging
  description: Charge your Tesla EV on excess solar, no internet required
  domain: automation
  source_url: https://raw.githubusercontent.com/michael-robbins/ha-snippets/main/blueprints/tesla_ev_solar_excess_charging.yaml
